name: docker-php84-nginx-apache-mysql9-mailpit

services:
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/security.conf:/etc/nginx/conf.d/security.conf
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 80:80
            - 443:443

    apache:
        image: httpd:2.4
        volumes:
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./apache/security.conf:/usr/local/apache2/conf/extra/security.conf
            - ../laravel:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 8000:80

    php:
        user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
        build:
            context: ./php
            args:
                HOST_UID: ${HOST_UID:-1000}
                HOST_GID: ${HOST_GID:-1000}
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ../laravel:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 9000:9000

    mysql:
        image: mysql:8.0
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
#        ports:
#            - 3306:3306

    mailpit:
        image: axllent/mailpit
        ports:
            - 8025:8025

volumes:
    mysql:
