version: "3"

services:
    php-apache:
        build: ./php-apache
        volumes:
            - ${WWW_ROOT}:/var/www
        ports:
            - 80:80
            - 443:443

    mysql:
        build: ./mysql
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: Asia/Tokyo
        ports:
            - 3306:3306

    maildev:
        image: maildev/maildev
        ports:
            - 8025:80

volumes:
    mysql:
